'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertCircle, CheckCircle2, Clock3, FilePenLine, Loader2, UserPlus } from 'lucide-react'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Card, CardContent } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'

export interface ManagedEditorRow { id: string; email: string; full_name: string; account_status: string; is_active: boolean; auth_user_id: number | null; auth_provider: string | null; last_login_at: string | null }

export function EditorManagement({ editors }: { editors: ManagedEditorRow[] }) {
  const router = useRouter(); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); setSuccess(null); try { const response = await fetch('/api/admin/editors', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName, email }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Editor belum dapat disimpan.'); setSuccess(`${result.editor.email} berhasil dipraotorisasi sebagai Editor.`); setFullName(''); setEmail(''); router.refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Editor belum dapat disimpan.') } finally { setLoading(false) } }
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.4fr)]"><Card className="h-fit border-none bg-primary/5"><CardContent className="p-7"><UserPlus className="mb-5 text-primary" size={30} /><h2 className="font-serif text-2xl text-text">Tambah Editor</h2><p className="mt-2 text-sm leading-6 text-text-muted">Praotorisasi email Google untuk ruang Editor. Editor tidak dapat melakukan review atau publikasi.</p><form className="mt-6 space-y-4" onSubmit={submit}><Input label="Nama lengkap" value={fullName} onChange={(event) => setFullName(event.target.value)} minLength={3} maxLength={150} required placeholder="Nama Editor" /><Input label="Email Google" type="email" value={email} onChange={(event) => setEmail(event.target.value)} maxLength={320} required placeholder="editor@example.com" />{error && <div className="flex gap-3 rounded-xl bg-error/10 p-4 text-sm text-error"><AlertCircle size={18} />{error}</div>}{success && <div className="flex gap-3 rounded-xl bg-success/10 p-4 text-sm text-success"><CheckCircle2 size={18} />{success}</div>}<Button className="w-full" disabled={loading}>{loading ? <Loader2 className="animate-spin" size={17} /> : <FilePenLine size={17} />}{loading ? 'Menyimpan...' : 'Praotorisasi Editor'}</Button></form></CardContent></Card><div className="space-y-4"><div><h2 className="font-serif text-2xl text-text">Editor terdaftar</h2><p className="mt-1 text-sm text-text-muted">{editors.length} profil Editor di Neon</p></div>{editors.map((editor) => { const linked = Boolean(editor.auth_user_id); const active = editor.account_status === 'active' && editor.is_active; return <Card key={editor.id} className="border-none bg-surface-2/40"><CardContent className="p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap gap-2"><h3 className="font-serif text-lg text-text">{editor.full_name}</h3><Badge variant={active ? 'success' : 'destructive'}>{active ? 'Aktif' : editor.account_status.replace('_', ' ')}</Badge></div><p className="mt-1 text-sm text-text-muted">{editor.email}</p></div><Badge variant={linked ? 'success' : 'warning'} className="w-fit">{linked ? <CheckCircle2 className="mr-1" size={13} /> : <Clock3 className="mr-1" size={13} />}{linked ? 'Google tertaut' : 'Menunggu login'}</Badge></div><p className="mt-4 border-t border-border pt-4 text-xs text-text-muted">Login terakhir: {editor.last_login_at ? new Date(editor.last_login_at).toLocaleString('id-ID') : 'Belum pernah'}</p></CardContent></Card> })}</div></div>
}
